apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: tomcat
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: my-tomcat
      labels:
        tier: frontend
        app: tomcat
    spec:
        containers:
            - name: snoop
              image: localhost:32000/snoop:dev
              imagePullPolicy: Always
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
