apiVersion: v1
kind: Pod
metadata:
  name: snoop
  labels:
    tier: frontend
spec:
  containers:
  - name: snoop
    image: localhost:32000/snoop:dev
    imagePullPolicy: Always
    ports:
    - containerPort: 8080

